version: "3.9"
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
