---
# Helm Chart Values: https://github.com/yaperos/helm-charts/blob/main/charts/yape-default/values.yaml
deploymentCommand:
  - "/bin/sh"
  - "-c"
  - |-
    source /vault/secrets/vars && source /vault/secrets/secrets && npm run start:prod

livenessProbe:
  httpGet:
    path: /
    port: app-expose
  failureThreshold: 2
  initialDelaySeconds: 20
  periodSeconds: 20
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: app-expose
  failureThreshold: 2
  initialDelaySeconds: 20
  periodSeconds: 20
  timeoutSeconds: 5

ingresses:
  - name: ms-nest-template
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_cache cache;
        proxy_cache_valid 200 10m;
        proxy_cache_valid 404 2s;
        proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
        add_header X-Age-I $upstream_http_date;
        add_header X-Cache-I $upstream_cache_status;
        add_header X-Frame-Options SAMEORIGIN always;
        add_header X-Content-Type-Options nosniff;
        proxy_hide_header Set-Cookie;    # Do not add the set-cookie header to the response to the client. Cookie is being added by Dynatrace and avoids caching when set
        proxy_ignore_headers Set-Cookie; # Ignore set-cookie header to cache policy.                       Cookie is being added by Dynatrace and avoids caching when set
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-max-age: "900"
      nginx.ingress.kubernetes.io/cors-allow-methods: "GET,HEAD,POST,OPTIONS"
      nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization,Content-Type,Bypass-Cache,Gql-Operation"
      nginx.ingress.kubernetes.io/server-snippet: |
        if ($request_method !~ ^(GET|HEAD|POST|OPTIONS)$ ) {
          return 406;
        }
    paths:
      - path: /
        pathType: Prefix
        serviceName: ms-nest-template
        servicePort: 80

serviceAccount:
  name: vault-auth

podAnnotations:
  vault.hashicorp.com/role: 'vault-auth'
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/agent-limits-cpu: "125m"
  vault.hashicorp.com/agent-limits-mem: "64Mi"
  vault.hashicorp.com/agent-requests-cpu: "25m"
  vault.hashicorp.com/agent-requests-mem: "32Mi"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/agent-inject-secret-vars: "app_envs/data/ms-nest-template/vars"
  vault.hashicorp.com/agent-inject-template-vars: |-
    {{- with secret "app_envs/data/ms-nest-template/vars" -}}
    {{ range $k, $v := .Data.data }}
    export {{ $k }}={{ $v }}
    {{ end }}
    {{- end -}}
  vault.hashicorp.com/agent-inject-secret-secrets: 'app_envs/data/ms-nest-template/secrets'
  vault.hashicorp.com/agent-inject-template-secrets: |
    {{- with secret "app_envs/data/ms-nest-template/secrets" -}}
    {{ range $k, $v := .Data.data }}
    export {{ $k }}={{ $v }}
    {{ end }}
    {{- end -}}
